apiVersion: v1
kind: Pod
metadata:
  name: rq-01
  namespace: default
spec:
  containers:
  - name: cont-01
    image: nginx
    ports:
      - containerPort: 80
        name: http
        protocol: "TCP"
    resources:
      requests: 
        cpu: "800mi"
        memory: "800Mi"
      limits:
        cpu: "900mi"
        memory: "900Mi"




