apiVersion: v1 
kind: Pod
metadata:
  name: test-limitrange-of-pod
  namespace: default
spec:
  containers:
  - name: cont-01
    image: nginx
    ports:
      - containerPort: 80

## If you set default LimitRange to Pod  automatically it will take the default resources to the pod

## when you describe or edit the pod you will get to see the limit range to the pod
###