apiVersion: v1
kind: Pod
metadata:
  name: min-max-mem
  namespace: app-01
spec:
  containers:
  - name: app
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: "1.5Gi"
      requests:
        memory: "600Mi"


