apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-pod-01
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: cont-01
        image: nginx
        ports:
          - containerPort: 80
            name: http
            protocol: "TCP"
        resources:
          requests: 
            cpu: "800mi"
            memory: "800Mi"
          limits:
            cpu: "900mi"
            memory: "900Mi"



